from PyQt5.QtCore import QThreadPool, QTimer
from PyQt5 import QtCore, QtGui, QtWidgets
import qdarktheme
import inspect
import sys
import os

# load outside c
from dep.py.loadLib import libs

# import outside py functions
from dep.py.functions import (
    openLinkDialog, changePage, FileDialog, 
    ErrorBox, get_Hashes, is_MD5_hash
)
from dep.py.settingsfunc import (
    Load_settings, SaveApply_settings
)
from dep.py.hashUpdate import HashWorker
from dep.py.scan import ScanWorker

# outside ui elements
from dep.ui_elements.dialogs.HashDialog import Ui_HashDialog



current_dir = os.path.dirname(os.path.realpath(__file__))

class Ui_MainWindow(object):
    # .self functions
    # scan file Thread
    def scan(self, current_dir, filepath, type):
        _self = self
        scan_pool = QThreadPool.globalInstance()
        scan_pool.start(ScanWorker(_self, current_dir, filepath, type).run)

    # Update Hashes Thread
    def HashUpdateTread(self, current_dir):
        _self = self
        self.timer = QTimer()
        self.timer.stop()

        # create update thread
        HashUpdate_pool = QThreadPool.globalInstance()
        HashUpdate_pool.start(HashWorker(_self, current_dir))

        # run update hash thread when the timer runs out
        self.timer.timeout.connect(lambda: HashWorker(_self, current_dir).run())

        # Get the hours and minutes defined by the user and define the timer delay
        UserDefinedInterval = self.UpdateInterval_timeEdit.time().toString("hh:mm:ss")
        hours, minutes, seconds = map(int, UserDefinedInterval.split(':'))
        _UserDefinedInterval = (hours * 3600 + minutes * 60) * 1000

        # start the timer with the user defined update time
        self.timer.start(_UserDefinedInterval)

    # get current function data
    def def_data(self):
        function_name = inspect.currentframe().f_back.f_code.co_name + "()"
        caller_frame = inspect.stack()[1]
        function_file_path = caller_frame.filename
        return (function_name,  ("\\"+os.path.relpath(function_file_path, current_dir)))
    
    # on close event
    def closeEvent(self, event):
        if self.worker:
            self.worker.stop()
            self.thread.quit()
            self.thread.wait()
        event.accept()

    # show hash dialog window
    def show_HashDialog(self):
        self.HashDialog_window = QtWidgets.QDialog()
        self.HashDialog_ui = Ui_HashDialog()
        self.HashDialog_ui.setupUi(self.HashDialog_window)
        result = self.HashDialog_window.exec_()
        # check if it was accepted or rejected(canceled)
        if result == QtWidgets.QDialog.Accepted:
            return self.HashDialog_ui._return()
        elif result == QtWidgets.QDialog.Rejected:
            return None
    

    # function rooting for self.
    def changePage(self, page, LoadingReason=None):
        return changePage(self, page, LoadingReason)
    def ErrorBox(self, Error, def_data, Title="Error"):
        return ErrorBox(self, Error, def_data, Title)
    def get_Hashes(self, filepath):
        return get_Hashes(self, filepath) 
    def is_MD5_hash(self, hash):
        return is_MD5_hash(self, hash)

    # Main Window
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 340)
        MainWindow.setMinimumSize(QtCore.QSize(710, 340))
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(5, -1, -1, 4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(MainWindow)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.HomePage = QtWidgets.QWidget()
        self.HomePage.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Europe))
        self.HomePage.setObjectName("HomePage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.HomePage)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ScanAHash_pushButton = QtWidgets.QPushButton(self.HomePage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ScanAHash_pushButton.setFont(font)
        self.ScanAHash_pushButton.setObjectName("ScanAHash_pushButton")
        self.gridLayout_3.addWidget(self.ScanAHash_pushButton, 1, 0, 1, 1)
        self.ScanAFile_pushButton = QtWidgets.QPushButton(self.HomePage)
        self.ScanAFile_pushButton.setMinimumSize(QtCore.QSize(130, 25))
        self.ScanAFile_pushButton.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ScanAFile_pushButton.setFont(font)
        self.ScanAFile_pushButton.setObjectName("ScanAFile_pushButton")
        self.gridLayout_3.addWidget(self.ScanAFile_pushButton, 0, 0, 1, 1)
        self.ReportAIssue_pushButton = QtWidgets.QPushButton(self.HomePage)
        self.ReportAIssue_pushButton.setMinimumSize(QtCore.QSize(80, 25))
        self.ReportAIssue_pushButton.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ReportAIssue_pushButton.setFont(font)
        self.ReportAIssue_pushButton.setObjectName("ReportAIssue_pushButton")
        self.gridLayout_3.addWidget(self.ReportAIssue_pushButton, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.HomePage_pushButton = QtWidgets.QPushButton(self.HomePage)
        self.HomePage_pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.HomePage_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.HomePage_pushButton.setStyleSheet("QPushButton {\n"
"  image: url(:/icons/icons/homepage_dark.svg);\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #525252\n"
"};")
        self.HomePage_pushButton.setText("")
        self.HomePage_pushButton.setFlat(False)
        self.HomePage_pushButton.setObjectName("HomePage_pushButton")
        self.verticalLayout_2.addWidget(self.HomePage_pushButton)
        self.SettingsPage_pushButton = QtWidgets.QPushButton(self.HomePage)
        self.SettingsPage_pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.SettingsPage_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.SettingsPage_pushButton.setAutoFillBackground(False)
        self.SettingsPage_pushButton.setStyleSheet("QPushButton {\n"
"  image: url(:/icons/icons/settingspage_dark.svg);\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #525252\n"
"};")
        self.SettingsPage_pushButton.setText("")
        self.SettingsPage_pushButton.setFlat(False)
        self.SettingsPage_pushButton.setObjectName("SettingsPage_pushButton")
        self.verticalLayout_2.addWidget(self.SettingsPage_pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.HomePage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Logo_label = QtWidgets.QLabel(self.HomePage)
        self.Logo_label.setMinimumSize(QtCore.QSize(40, 45))
        self.Logo_label.setMaximumSize(QtCore.QSize(40, 45))
        self.Logo_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Logo_label.setAutoFillBackground(False)
        self.Logo_label.setStyleSheet("background-image: url(:/logo/logo/logo_dark.svg); background-repeat: no-repeat;")
        self.Logo_label.setText("")
        self.Logo_label.setTextFormat(QtCore.Qt.AutoText)
        self.Logo_label.setScaledContents(True)
        self.Logo_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Logo_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Logo_label.setObjectName("Logo_label")
        self.horizontalLayout_2.addWidget(self.Logo_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.HomePage)
        self.LoadingPage = QtWidgets.QWidget()
        self.LoadingPage.setObjectName("LoadingPage")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.LoadingPage)
        self.gridLayout_7.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_7.setHorizontalSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_22 = QtWidgets.QLabel(self.LoadingPage)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem3, 5, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.LoadingPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem4, 1, 0, 1, 1)
        self.LoadingReason_label = QtWidgets.QLabel(self.LoadingPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LoadingReason_label.setFont(font)
        self.LoadingReason_label.setAlignment(QtCore.Qt.AlignCenter)
        self.LoadingReason_label.setWordWrap(True)
        self.LoadingReason_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.LoadingReason_label.setObjectName("LoadingReason_label")
        self.gridLayout_7.addWidget(self.LoadingReason_label, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.LoadingPage)
        self.ResultsPage = QtWidgets.QWidget()
        self.ResultsPage.setMinimumSize(QtCore.QSize(634, 0))
        self.ResultsPage.setObjectName("ResultsPage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.ResultsPage)
        self.gridLayout_6.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_6.setHorizontalSpacing(5)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 0, 3, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(10, 5, 0, -1)
        self.formLayout_3.setHorizontalSpacing(6)
        self.formLayout_3.setVerticalSpacing(4)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.InputDisplay_label = QtWidgets.QLabel(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.InputDisplay_label.setFont(font)
        self.InputDisplay_label.setObjectName("InputDisplay_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.InputDisplay_label)
        self.label_6 = QtWidgets.QLabel(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.MD5_HashDisplay_label = QtWidgets.QLabel(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.MD5_HashDisplay_label.setFont(font)
        self.MD5_HashDisplay_label.setObjectName("MD5_HashDisplay_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.MD5_HashDisplay_label)
        self.label_9 = QtWidgets.QLabel(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.HashCheck_noInput_checkBox = QtWidgets.QCheckBox(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.HashCheck_noInput_checkBox.setFont(font)
        self.HashCheck_noInput_checkBox.setCheckable(True)
        self.HashCheck_noInput_checkBox.setObjectName("HashCheck_noInput_checkBox")
        self.horizontalLayout_5.addWidget(self.HashCheck_noInput_checkBox)
        self.VirusTotalCheck_noInput_checkBox = QtWidgets.QCheckBox(self.ResultsPage)
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(10)
        self.VirusTotalCheck_noInput_checkBox.setFont(font)
        self.VirusTotalCheck_noInput_checkBox.setObjectName("VirusTotalCheck_noInput_checkBox")
        self.horizontalLayout_5.addWidget(self.VirusTotalCheck_noInput_checkBox)
        self.MetaDefenderCheck_noInput_checkBox = QtWidgets.QCheckBox(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MetaDefenderCheck_noInput_checkBox.setFont(font)
        self.MetaDefenderCheck_noInput_checkBox.setObjectName("MetaDefenderCheck_noInput_checkBox")
        self.horizontalLayout_5.addWidget(self.MetaDefenderCheck_noInput_checkBox)
        self.formLayout_3.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_8 = QtWidgets.QLabel(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.HashCheckDetection_noInput_checkBox = QtWidgets.QCheckBox(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.HashCheckDetection_noInput_checkBox.setFont(font)
        self.HashCheckDetection_noInput_checkBox.setCheckable(True)
        self.HashCheckDetection_noInput_checkBox.setChecked(False)
        self.HashCheckDetection_noInput_checkBox.setObjectName("HashCheckDetection_noInput_checkBox")
        self.horizontalLayout.addWidget(self.HashCheckDetection_noInput_checkBox)
        self.formLayout_3.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_13 = QtWidgets.QLabel(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.ResultsPage)
        self.label_14.setStyleSheet("color: green;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.ResultsPage)
        self.label_15.setStyleSheet("color: red;")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.ResultsPage)
        self.label_16.setStyleSheet("color: orange;")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.ResultsPage)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.ResultsPage)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.ResultsPage)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.ResultsPage)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.VirusTotal_harmless_results_label = QtWidgets.QLabel(self.ResultsPage)
        self.VirusTotal_harmless_results_label.setStyleSheet("color: green;")
        self.VirusTotal_harmless_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.VirusTotal_harmless_results_label.setObjectName("VirusTotal_harmless_results_label")
        self.horizontalLayout_8.addWidget(self.VirusTotal_harmless_results_label)
        self.VirusTotal_malicious_results_label = QtWidgets.QLabel(self.ResultsPage)
        self.VirusTotal_malicious_results_label.setStyleSheet("color: red;")
        self.VirusTotal_malicious_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.VirusTotal_malicious_results_label.setObjectName("VirusTotal_malicious_results_label")
        self.horizontalLayout_8.addWidget(self.VirusTotal_malicious_results_label)
        self.VirusTotal_suspicious_results_label = QtWidgets.QLabel(self.ResultsPage)
        self.VirusTotal_suspicious_results_label.setStyleSheet("color: orange;")
        self.VirusTotal_suspicious_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.VirusTotal_suspicious_results_label.setObjectName("VirusTotal_suspicious_results_label")
        self.horizontalLayout_8.addWidget(self.VirusTotal_suspicious_results_label)
        self.VirusTotal_timeout_results_label = QtWidgets.QLabel(self.ResultsPage)
        self.VirusTotal_timeout_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.VirusTotal_timeout_results_label.setObjectName("VirusTotal_timeout_results_label")
        self.horizontalLayout_8.addWidget(self.VirusTotal_timeout_results_label)
        self.VirusTotal_unsupported_results_label = QtWidgets.QLabel(self.ResultsPage)
        self.VirusTotal_unsupported_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.VirusTotal_unsupported_results_label.setObjectName("VirusTotal_unsupported_results_label")
        self.horizontalLayout_8.addWidget(self.VirusTotal_unsupported_results_label)
        self.VirusTotal_undetected_results_label = QtWidgets.QLabel(self.ResultsPage)
        self.VirusTotal_undetected_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.VirusTotal_undetected_results_label.setObjectName("VirusTotal_undetected_results_label")
        self.horizontalLayout_8.addWidget(self.VirusTotal_undetected_results_label)
        self.VirusTotal_failure_results_label = QtWidgets.QLabel(self.ResultsPage)
        self.VirusTotal_failure_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.VirusTotal_failure_results_label.setObjectName("VirusTotal_failure_results_label")
        self.horizontalLayout_8.addWidget(self.VirusTotal_failure_results_label)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.formLayout_3.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_8)
        self.label_26 = QtWidgets.QLabel(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_28 = QtWidgets.QLabel(self.ResultsPage)
        self.label_28.setStyleSheet("color: red;")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_10.addWidget(self.label_28)
        self.label_27 = QtWidgets.QLabel(self.ResultsPage)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_10.addWidget(self.label_27)
        self.label_31 = QtWidgets.QLabel(self.ResultsPage)
        self.label_31.setStyleSheet("color: green;")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_10.addWidget(self.label_31)
        self.label_33 = QtWidgets.QLabel(self.ResultsPage)
        self.label_33.setStyleSheet("color: orange;")
        self.label_33.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_10.addWidget(self.label_33)
        self.label_35 = QtWidgets.QLabel(self.ResultsPage)
        self.label_35.setStyleSheet("color: green;")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_10.addWidget(self.label_35)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.MetaDefender_EngineDetections_results_label = QtWidgets.QLabel(self.ResultsPage)
        self.MetaDefender_EngineDetections_results_label.setStyleSheet("color: red;")
        self.MetaDefender_EngineDetections_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MetaDefender_EngineDetections_results_label.setObjectName("MetaDefender_EngineDetections_results_label")
        self.horizontalLayout_12.addWidget(self.MetaDefender_EngineDetections_results_label)
        self.MetaDefender_Engines_results_label = QtWidgets.QLabel(self.ResultsPage)
        self.MetaDefender_Engines_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MetaDefender_Engines_results_label.setObjectName("MetaDefender_Engines_results_label")
        self.horizontalLayout_12.addWidget(self.MetaDefender_Engines_results_label)
        self.MetaDefender_DetectionPercentage_results_label = QtWidgets.QLabel(self.ResultsPage)
        self.MetaDefender_DetectionPercentage_results_label.setStyleSheet("color: green;")
        self.MetaDefender_DetectionPercentage_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MetaDefender_DetectionPercentage_results_label.setObjectName("MetaDefender_DetectionPercentage_results_label")
        self.horizontalLayout_12.addWidget(self.MetaDefender_DetectionPercentage_results_label)
        self.MetaDefender_UserVotesMalicious_results_label = QtWidgets.QLabel(self.ResultsPage)
        self.MetaDefender_UserVotesMalicious_results_label.setStyleSheet("color: orange;")
        self.MetaDefender_UserVotesMalicious_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MetaDefender_UserVotesMalicious_results_label.setObjectName("MetaDefender_UserVotesMalicious_results_label")
        self.horizontalLayout_12.addWidget(self.MetaDefender_UserVotesMalicious_results_label)
        self.MetaDefender_UserVotesHarmless_results_label = QtWidgets.QLabel(self.ResultsPage)
        self.MetaDefender_UserVotesHarmless_results_label.setStyleSheet("color: green;")
        self.MetaDefender_UserVotesHarmless_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MetaDefender_UserVotesHarmless_results_label.setObjectName("MetaDefender_UserVotesHarmless_results_label")
        self.horizontalLayout_12.addWidget(self.MetaDefender_UserVotesHarmless_results_label)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_12)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.formLayout_3.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_9)
        self.label_29 = QtWidgets.QLabel(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.SHA1_HashDisplay_label = QtWidgets.QLabel(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SHA1_HashDisplay_label.setFont(font)
        self.SHA1_HashDisplay_label.setObjectName("SHA1_HashDisplay_label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.SHA1_HashDisplay_label)
        self.label_32 = QtWidgets.QLabel(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.SHA256_HashDisplay_label = QtWidgets.QLabel(self.ResultsPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SHA256_HashDisplay_label.setFont(font)
        self.SHA256_HashDisplay_label.setObjectName("SHA256_HashDisplay_label")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.SHA256_HashDisplay_label)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        self.gridLayout_6.addLayout(self.formLayout_3, 1, 3, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Logo_label_3 = QtWidgets.QLabel(self.ResultsPage)
        self.Logo_label_3.setMinimumSize(QtCore.QSize(40, 45))
        self.Logo_label_3.setMaximumSize(QtCore.QSize(40, 45))
        self.Logo_label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Logo_label_3.setAutoFillBackground(False)
        self.Logo_label_3.setStyleSheet("background-image: url(:/logo/logo/logo_dark.svg); background-repeat: no-repeat;")
        self.Logo_label_3.setText("")
        self.Logo_label_3.setTextFormat(QtCore.Qt.AutoText)
        self.Logo_label_3.setScaledContents(True)
        self.Logo_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Logo_label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Logo_label_3.setObjectName("Logo_label_3")
        self.horizontalLayout_4.addWidget(self.Logo_label_3)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_6.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.HomePage_pushButton_3 = QtWidgets.QPushButton(self.ResultsPage)
        self.HomePage_pushButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.HomePage_pushButton_3.setMaximumSize(QtCore.QSize(40, 40))
        self.HomePage_pushButton_3.setStyleSheet("QPushButton {\n"
"  image: url(:/icons/icons/homepage_dark.svg);\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #525252\n"
"};")
        self.HomePage_pushButton_3.setText("")
        self.HomePage_pushButton_3.setFlat(False)
        self.HomePage_pushButton_3.setObjectName("HomePage_pushButton_3")
        self.verticalLayout_6.addWidget(self.HomePage_pushButton_3)
        self.SettingsPage_pushButton_3 = QtWidgets.QPushButton(self.ResultsPage)
        self.SettingsPage_pushButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.SettingsPage_pushButton_3.setMaximumSize(QtCore.QSize(40, 40))
        self.SettingsPage_pushButton_3.setStyleSheet("QPushButton {\n"
"  image: url(:/icons/icons/settingspage_dark.svg);\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #525252\n"
"};")
        self.SettingsPage_pushButton_3.setText("")
        self.SettingsPage_pushButton_3.setFlat(False)
        self.SettingsPage_pushButton_3.setObjectName("SettingsPage_pushButton_3")
        self.verticalLayout_6.addWidget(self.SettingsPage_pushButton_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.gridLayout_6.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.ResultsPage)
        self.SettingsPage = QtWidgets.QWidget()
        self.SettingsPage.setObjectName("SettingsPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.SettingsPage)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setHorizontalSpacing(5)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.HomePage_pushButton_2 = QtWidgets.QPushButton(self.SettingsPage)
        self.HomePage_pushButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.HomePage_pushButton_2.setMaximumSize(QtCore.QSize(40, 40))
        self.HomePage_pushButton_2.setStyleSheet("QPushButton {\n"
"  image: url(:/icons/icons/homepage_dark.svg);\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #525252\n"
"};")
        self.HomePage_pushButton_2.setText("")
        self.HomePage_pushButton_2.setFlat(False)
        self.HomePage_pushButton_2.setObjectName("HomePage_pushButton_2")
        self.verticalLayout_4.addWidget(self.HomePage_pushButton_2)
        self.SettingsPage_pushButton_2 = QtWidgets.QPushButton(self.SettingsPage)
        self.SettingsPage_pushButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.SettingsPage_pushButton_2.setMaximumSize(QtCore.QSize(40, 40))
        self.SettingsPage_pushButton_2.setStyleSheet("QPushButton {\n"
"  image: url(:/icons/icons/settingspage_dark.svg);\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #525252\n"
"};")
        self.SettingsPage_pushButton_2.setText("")
        self.SettingsPage_pushButton_2.setFlat(False)
        self.SettingsPage_pushButton_2.setObjectName("SettingsPage_pushButton_2")
        self.verticalLayout_4.addWidget(self.SettingsPage_pushButton_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Logo_label_2 = QtWidgets.QLabel(self.SettingsPage)
        self.Logo_label_2.setMinimumSize(QtCore.QSize(40, 45))
        self.Logo_label_2.setMaximumSize(QtCore.QSize(40, 45))
        self.Logo_label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Logo_label_2.setAutoFillBackground(False)
        self.Logo_label_2.setStyleSheet("background-image: url(:/logo/logo/logo_dark.svg); background-repeat: no-repeat;")
        self.Logo_label_2.setText("")
        self.Logo_label_2.setTextFormat(QtCore.Qt.AutoText)
        self.Logo_label_2.setScaledContents(True)
        self.Logo_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Logo_label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Logo_label_2.setObjectName("Logo_label_2")
        self.horizontalLayout_3.addWidget(self.Logo_label_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(10, 10, 10, -1)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem8)
        self.label_3 = QtWidgets.QLabel(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.theme_comboBox = QtWidgets.QComboBox(self.SettingsPage)
        self.theme_comboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.theme_comboBox.setFont(font)
        self.theme_comboBox.setObjectName("theme_comboBox")
        self.theme_comboBox.addItem("")
        self.theme_comboBox.addItem("")
        self.theme_comboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.theme_comboBox)
        self.SaveSettings_pushButton = QtWidgets.QPushButton(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SaveSettings_pushButton.setFont(font)
        self.SaveSettings_pushButton.setObjectName("SaveSettings_pushButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.SaveSettings_pushButton)
        self.label_10 = QtWidgets.QLabel(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem9)
        self.label_11 = QtWidgets.QLabel(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Method_HashCheck_checkBox = QtWidgets.QCheckBox(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Method_HashCheck_checkBox.setFont(font)
        self.Method_HashCheck_checkBox.setObjectName("Method_HashCheck_checkBox")
        self.horizontalLayout_6.addWidget(self.Method_HashCheck_checkBox)
        self.Method_VirusTotal_checkBox = QtWidgets.QCheckBox(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Method_VirusTotal_checkBox.setFont(font)
        self.Method_VirusTotal_checkBox.setObjectName("Method_VirusTotal_checkBox")
        self.horizontalLayout_6.addWidget(self.Method_VirusTotal_checkBox)
        self.Method_MetaDefender_checkBox = QtWidgets.QCheckBox(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Method_MetaDefender_checkBox.setFont(font)
        self.Method_MetaDefender_checkBox.setObjectName("Method_MetaDefender_checkBox")
        self.horizontalLayout_6.addWidget(self.Method_MetaDefender_checkBox)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem10)
        self.label_12 = QtWidgets.QLabel(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.VirusTotal_ApiKey_lineEdit = QtWidgets.QLineEdit(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.VirusTotal_ApiKey_lineEdit.setFont(font)
        self.VirusTotal_ApiKey_lineEdit.setFrame(True)
        self.VirusTotal_ApiKey_lineEdit.setObjectName("VirusTotal_ApiKey_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.VirusTotal_ApiKey_lineEdit)
        self.label_23 = QtWidgets.QLabel(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.UpdateHashes_checkBox = QtWidgets.QCheckBox(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UpdateHashes_checkBox.setFont(font)
        self.UpdateHashes_checkBox.setObjectName("UpdateHashes_checkBox")
        self.horizontalLayout_9.addWidget(self.UpdateHashes_checkBox)
        self.UpdateInterval_timeEdit = QtWidgets.QTimeEdit(self.SettingsPage)
        self.UpdateInterval_timeEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.UpdateInterval_timeEdit.setFrame(True)
        self.UpdateInterval_timeEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(1, 0, 0)))
        self.UpdateInterval_timeEdit.setCalendarPopup(False)
        self.UpdateInterval_timeEdit.setObjectName("UpdateInterval_timeEdit")
        self.horizontalLayout_9.addWidget(self.UpdateInterval_timeEdit)
        self.label_24 = QtWidgets.QLabel(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_9.addWidget(self.label_24)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.label_25 = QtWidgets.QLabel(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.MetaDefender_ApiKey_lineEdit = QtWidgets.QLineEdit(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MetaDefender_ApiKey_lineEdit.setFont(font)
        self.MetaDefender_ApiKey_lineEdit.setObjectName("MetaDefender_ApiKey_lineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.MetaDefender_ApiKey_lineEdit)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.SettingsPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.SettingsPage)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.Version = QtWidgets.QLabel(MainWindow)
        self.Version.setObjectName("Version")
        self.verticalLayout_3.addWidget(self.Version)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        
        self.retranslateUi(MainWindow)
        self.changePage("HomePage")
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # disable checkBoxes
        self.HashCheck_noInput_checkBox.setEnabled(False)
        self.HashCheckDetection_noInput_checkBox.setEnabled(False)
        self.Method_HashCheck_checkBox.setEnabled(False)
        self.Method_HashCheck_checkBox.setChecked(True)
        self.VirusTotalCheck_noInput_checkBox.setEnabled(False)
        self.MetaDefenderCheck_noInput_checkBox.setEnabled(False)
        
        # load shared libs and define arg types
        libs(self, current_dir)
        
        # side buttons
        self.HomePage_pushButton.clicked.connect(lambda: self.changePage("HomePage"))
        self.SettingsPage_pushButton.clicked.connect(lambda: self.changePage("SettingsPage"))
        self.HomePage_pushButton_2.clicked.connect(lambda: self.changePage( "HomePage"))
        self.SettingsPage_pushButton_2.clicked.connect(lambda: self.changePage("SettingsPage"))
        self.HomePage_pushButton_3.clicked.connect(lambda: self.changePage( "HomePage"))
        self.SettingsPage_pushButton_3.clicked.connect(lambda: self.changePage("SettingsPage"))
        
        # buttons (Home Page)
        self.ReportAIssue_pushButton.clicked.connect(lambda: openLinkDialog("https://github.com/cookie0o/betterPYAV/issues"))
        self.ScanAFile_pushButton.clicked.connect(lambda: (
            self.changePage("LoadingPage", "Waiting for Input"),
            self.scan(current_dir, FileDialog(self, MainWindow), "HashFile")
        ))
        self.ScanAHash_pushButton.clicked.connect (lambda: (
            self.changePage("LoadingPage", "Waiting for Input"),
            self.scan(current_dir, self.show_HashDialog(), "HashFile")
        ))
        
        
        # buttons (Settings Page)
        self.SaveSettings_pushButton.clicked.connect(lambda: SaveApply_settings(self, current_dir))
        
        
        # load and apply settings
        Load_settings(self, current_dir)
        MainWindow.show()

        self.HashUpdateTread(current_dir)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "Home Page"))
        self.ScanAHash_pushButton.setText(_translate("MainWindow", "Scan a Hash"))
        self.ScanAFile_pushButton.setText(_translate("MainWindow", "Scan a File"))
        self.ReportAIssue_pushButton.setText(_translate("MainWindow", "Report a Issue"))
        self.label.setText(_translate("MainWindow", "Home Page"))
        self.label_22.setText(_translate("MainWindow", "This might take a while..."))
        self.label_21.setText(_translate("MainWindow", "Loading Page"))
        self.LoadingReason_label.setText(_translate("MainWindow", "Loading"))
        self.label_5.setText(_translate("MainWindow", "Results Page"))
        self.label_7.setText(_translate("MainWindow", "Input:"))
        self.InputDisplay_label.setText(_translate("MainWindow", "None"))
        self.label_6.setText(_translate("MainWindow", "MD5-Hash:"))
        self.MD5_HashDisplay_label.setText(_translate("MainWindow", "None"))
        self.label_9.setText(_translate("MainWindow", "Methods Used:"))
        self.HashCheck_noInput_checkBox.setText(_translate("MainWindow", "Hash Check"))
        self.VirusTotalCheck_noInput_checkBox.setText(_translate("MainWindow", "Virus Total"))
        self.MetaDefenderCheck_noInput_checkBox.setText(_translate("MainWindow", "MetaDefender"))
        self.label_8.setText(_translate("MainWindow", "Detections:"))
        self.HashCheckDetection_noInput_checkBox.setText(_translate("MainWindow", "Hash Check"))
        self.label_13.setText(_translate("MainWindow", "Virus Total:"))
        self.label_14.setText(_translate("MainWindow", "harmless"))
        self.label_15.setText(_translate("MainWindow", "malicious"))
        self.label_16.setText(_translate("MainWindow", "suspicious"))
        self.label_17.setText(_translate("MainWindow", "timeout"))
        self.label_18.setText(_translate("MainWindow", "unsupported"))
        self.label_19.setText(_translate("MainWindow", "undetected"))
        self.label_20.setText(_translate("MainWindow", "failure"))
        self.VirusTotal_harmless_results_label.setText(_translate("MainWindow", "0"))
        self.VirusTotal_malicious_results_label.setText(_translate("MainWindow", "0"))
        self.VirusTotal_suspicious_results_label.setText(_translate("MainWindow", "0"))
        self.VirusTotal_timeout_results_label.setText(_translate("MainWindow", "0"))
        self.VirusTotal_unsupported_results_label.setText(_translate("MainWindow", "0"))
        self.VirusTotal_undetected_results_label.setText(_translate("MainWindow", "0"))
        self.VirusTotal_failure_results_label.setText(_translate("MainWindow", "0"))
        self.label_26.setText(_translate("MainWindow", "MetaDefender:"))
        self.label_28.setText(_translate("MainWindow", "Engine Detections"))
        self.label_27.setText(_translate("MainWindow", "Engines"))
        self.label_31.setText(_translate("MainWindow", "Detection %"))
        self.label_33.setText(_translate("MainWindow", "User Votes malicious"))
        self.label_35.setText(_translate("MainWindow", "User Votes harmless"))
        self.MetaDefender_EngineDetections_results_label.setText(_translate("MainWindow", "0"))
        self.MetaDefender_Engines_results_label.setText(_translate("MainWindow", "0"))
        self.MetaDefender_DetectionPercentage_results_label.setText(_translate("MainWindow", "0"))
        self.MetaDefender_UserVotesMalicious_results_label.setText(_translate("MainWindow", "0"))
        self.MetaDefender_UserVotesHarmless_results_label.setText(_translate("MainWindow", "0"))
        self.label_29.setText(_translate("MainWindow", "SHA1-Hash:"))
        self.SHA1_HashDisplay_label.setText(_translate("MainWindow", "None"))
        self.label_32.setText(_translate("MainWindow", "SHA256-Hash:"))
        self.SHA256_HashDisplay_label.setText(_translate("MainWindow", "None"))
        self.label_4.setText(_translate("MainWindow", "UI SETTINGS"))
        self.label_3.setText(_translate("MainWindow", "Theme"))
        self.theme_comboBox.setItemText(0, _translate("MainWindow", "auto"))
        self.theme_comboBox.setItemText(1, _translate("MainWindow", "dark"))
        self.theme_comboBox.setItemText(2, _translate("MainWindow", "light"))
        self.SaveSettings_pushButton.setText(_translate("MainWindow", "Save Settings"))
        self.label_10.setText(_translate("MainWindow", "SCAN SETTINS"))
        self.label_11.setText(_translate("MainWindow", "Methods"))
        self.Method_HashCheck_checkBox.setText(_translate("MainWindow", "Hash Check"))
        self.Method_VirusTotal_checkBox.setText(_translate("MainWindow", "Virus Total File/Hash scan"))
        self.Method_MetaDefender_checkBox.setText(_translate("MainWindow", "MetaDefender File/Hash scan"))
        self.label_12.setText(_translate("MainWindow", "VirusTotal Api Key"))
        self.label_23.setText(_translate("MainWindow", "Hash Update"))
        self.UpdateHashes_checkBox.setText(_translate("MainWindow", "Update Hashes from @MalwareBazaar every"))
        self.UpdateInterval_timeEdit.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.label_24.setText(_translate("MainWindow", "hour(s)."))
        self.label_25.setText(_translate("MainWindow", "MetaDefender Api Key"))
        self.label_2.setText(_translate("MainWindow", "Settings Page"))
        self.Version.setText(_translate("MainWindow", f"Version: {QtWidgets.QApplication.applicationVersion()}"))
import dep.ui_res.ui_rc


def main(appName, appVersion):
    # enable and handle high dpi displays
    qdarktheme.enable_hi_dpi()
    if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
        QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
    if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
        QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
        
    # create application
    app = QtWidgets.QApplication(sys.argv)
    # define values
    app.setApplicationName(appName +" "+ appVersion)
    app.setApplicationVersion(appVersion)
    # build
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    
    # show ui
    sys.exit(app.exec_())
    
    
if __name__ == "__main__":
    # open file and read app info
    with open (os.path.join(current_dir, "dep/appInfo.txt")) as F:
        appName = F.readline()
        appVersion = F.readline()
    F.close()
    
    # start app
    main(appName, appVersion)